# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '11.0'

target 'C:\Users\aflee\groceries\platforms\ios\MyApp' do
	project 'C:\Users\aflee\groceries\platforms\ios\MyApp.xcodeproj'

end
